### PR TITLE
Remove build artifacts and add them to .gitignore

### PR DESCRIPTION
**Pull request by LiraNuna**
It's a bad practice to have build artifacts in the repo - it seems like some of them were added to the `.gitignore` file but somehow still ended in the repo.

### CODE REVIEW

**Comment by LiraNuna** [comment]
I'm new to this pull request thing, I'll branch and separate the commits.

**Comment by christianalfoni** [comment]
You want to take over the project @LiraNuna ? I have no time to follow it up and you made some great updates here :) I could move it to your account if you want?

**Comment by LiraNuna** [comment]
@christianalfoni I'd love to but I wouldn't want to take credit for it. After all, you're the original author.

**Comment by christianalfoni** [comment]
Okay, let me add you as collaborator at least then :) So you can make changes without waiting for me :)

**Pull request closed without merging**
